routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Trang chủ
Route::get('/', 'ShopController@index')->name('shop.home');
// Liên Hệ

// Chi tiet sản phẩn
Route::get('/chi-tiet-san-pham/{slug}_{id}', 'ShopController@getProduct')->name('shop.product');

// Tìm kiếm
Route::get('/tim-kiem', 'ShopController@search')->name('shop.search');

// Thêm sản phẩm vào giỏ hàng hompage
Route::get('/dat-hang/them-sp-vao-gio-hang/{id}', 'CartController@addToCart')->name('shop.cart.add-to-cart');

// Xóa SP khỏi giỏ hàng
Route::get('/dat-hang/xoa-sp-gio-hang/{id}', 'CartController@removeToCart')->name('shop.cart.remove-to-cart');

//Them san pham trong gio hang
Route::get('/dat-hang/xem-san-pham-trong-gio-hang/', 'CartController@ViewListCart')->name('shop.cart.add-view-cart');


// Cập nhật giỏ hàng
Route::get('/dat-hang/cap-nhat-gio-hang/{id}/{quanty}', 'CartController@SaveListItemCart')->name('shop.cart.update-to-cart');

// Áp dụng giảm giá
Route::get('/dat-hang/ma-giam-gia', 'CartController@checkCoupon')->name('shop.cart.check-coupon');


// Hủy đơn hàng
Route::get('/dat-hang/huy-don-hang', 'CartController@destroy')->name('shop.cart.destroy');

// Đặt hàng
Route::get('/dat-hang', 'CartController@index')->name('shop.cart');
// Thanh toán
Route::get('/thanh-toan', 'CartController@checkout')->name('shop.cart.checkout');

Route::post('/thanh-toan', 'CartController@postCheckout')->name('shop.cart.checkout');
// // Thanh toán
Route::get('/lien-he', 'ContactController@create')->name('shop.contact');

Route::post('/lien-he', 'ContactController@store')->name('shop.contact.store');
// Route::resource('contact', 'ContactController');
//comments
Route::post('/comment/{blog_id}','CommentController@createBlog')->name('comments.create');
Route::post('/comments/{product_id}','CommentController@store')->name('comments.store');

/////////////////////////////////////////
// Đăng nhập
Route::get('/admin/login', 'AdminController@login')->name('admin.login');

// Đăng xuất
Route::get('/admin/logout', 'AdminController@logout')->name('admin.logout');
//tra cứu
Route::get('/tk', 'ShopController@sorder')->name('shop.sorder');
Route::get('/tra-cuu', 'ShopController@viewsearchorder')->name('shop.viewsearchorder');
Route::post('/admin/postLogin', 'AdminController@postLogin')->name('admin.postLogin');
Route::group(['prefix' => 'admin','as' => 'admin.','middleware' => ['CheckLogin']], function() {

	Route::get('/', 'AdminController@index')->name('dashboard');

    // Router cho category
	Route::resource('category', 'CategoryController');

    // Router cho Vendor
	   Route::resource('vendor','VendorController');


   	// Router cho Banner
	   Route::resource('banner','BannerController');

   	// Router cho Brand
	   Route::resource('brand','BrandController');
	   Route::get('searchBrand','BrandController@searchBrand');

   	// Router cho Product
	   Route::resource('product','ProductController');
	   Route::get('searchProduct','ProductController@searchProduct');

   	// Router cho User
	   Route::resource('user','UserController');

	// Router cho Image Product
	   Route::resource('imageUpload','ImageUploadController');

   	// Router cho Blog
   		Route::resource('blog','BlogController');
   		Route::get('searchBlog','BlogController@searchBlog');

   	// Router cho Order
   		Route::resource('order','OrderController');
   		Route::get('searchOrder','OrderController@searchOrder');

   	// Router cho Contact
   		Route::get('contact','ContactController@index')->name('contact.index');
   		Route::get('contact/{contact}/edit','ContactController@edit')->name('contact.edit');
   		Route::put('contact/{contact}','ContactController@update')->name('contact.update');
   		Route::patch('contact/{contact}','ContactController@update')->name('contact.update');
   		Route::get('searchContact','ContactController@searchContact');

   	// Router cho Coupon
   		Route::resource('coupon', 'CouponController');
   		Route::get('searchCoupon','CouponController@searchCoupon');

   	 // Cau Hinh Website
        Route::resource('setting', 'SettingController');
   		Route::resource('page', 'PageController');
   		Route::resource('AboutUs','AboutUsController');
   		Route::get('listicon','ListIconController@index')->name('listicon');
});
Route::get('forgot-password','AdminController@forgot')->name('forgot');
Route::post('forgot-password','AdminController@getForgotPassword')->name('getForgot');
Route::get('resetPassword/{token}','AdminController@resetPassword')->name('resetPassword');
Route::post('resetPassword','AdminController@newPass')->name('newPass');
//
Route::get('/danh-muc/{slug}', 'ShopController@getProductsByCategory')->name('shop.category');
Route::get('/blogs-detalis/{slug}_{id}.html', 'ShopController@ViewBlog')->name('shop.blog');
Route::get('/blogs-detalis', 'ShopController@BlogDetails')->name('shop.blog-detalis');
Route::get('/danh-muc/{slug}/filter','ShopController@filter')->name('shop.filter');
Route::get('/{slug}/{id}', 'ShopController@getpage')->name('shop.page');
Route::get('/{slug}', 'GeneralController@notfound')->name('shop.notfound');

resources/views/admin/page/create.blade.php
@extends('admin.layouts.main')
@section('content')

<section class="content-header">
    <div class="row page-title">
        <div class="col-md-12">
            <div aria-label="breadcrumb" class="float-right mt-1">
                <a class="btn btn-primary" href="{{route('admin.page.index')}}">Danh sách</a>
            </div>
            <span><b> <a class="text-dark" href="{{route('admin.page.index')}}">Danh sách</a> / <a class="text-dark" href="javascript:void(0)"> Thêm mới page</a> </b></span>
        </div>
    </div>
</section>

<section class="content">
    <div class="card">
        <div class="card-body">

            <form role="form" action="{{route('admin.page.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tiêu Đề</label>
                        <input type="text" class="form-control" id="title" name="title" placeholder="Nhập tên">
                        @error('title')
                            <label class="col-lg-12 col-form-label text-danger">{{ $message }}</label>
                            @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Url(Liên kết tùy chỉnh)</label>
                        <input type="text" class="form-control" id="slug" name="url" placeholder="Nhập liên kết tùy chỉnh">
                    </div>
                    <div class="form-group">
                        <label for="description">Mô tả</label>
                        <textarea value="" id="editor1" name="description" class="form-control" rows="10" ></textarea>
                    </div>
                    <div class="form-group mb-3">
                        <div class="custom-control custom-switch mb-2">
                            <input  type="checkbox" class="custom-control-input" id="customSwitch1" value="1" checked="" name="is_active">
                            <label class="custom-control-label" for="customSwitch1">Trạng thái</label>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Tạo</button>
            </form>

        </div>
    </div>
    <!-- /.row -->
</section>
@endsection

@section('my_javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            $(".btn-success").click(function(){
                var html = $(".clone").html();
                $(".increment").after(html);
            });
            $("body").on("click",".btn-danger",function(){
                $(this).parents(".control-group").remove();
            });
        });
        $(document).ready(function() {
            // setup textarea sử dụng plugin CKeditor
            var _ckeditor = CKEDITOR.replace('editor1',{
                filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
                filebrowserImageBrowseUrl: '{{ asset('backend/assets/js/pages/ckfinder/ckfinder.html?type=Images') }}',
                filebrowserFlashBrowseUrl: '{{ asset('backend/assets/js/pages/ckfinder/ckfinder.html?type=Flash') }}',
                filebrowserUploadUrl: '{{ asset('backend/assets/js/pages/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
                filebrowserImageUploadUrl: '{{ asset('backend/assets/js/pages/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
                filebrowserFlashUploadUrl: '{{ asset('backend/assets/js/pages/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}',
                extraPlugins: 'image2'
            });
            _ckeditor.config.height = 200; // thiết lập chiều cao
        });
    </script>
@endsection

resources/views/admin/page/edit.blade.php
@extends('admin.layouts.main')
@section('content')

<section class="content-header">
    <div class="row page-title">
        <div class="col-md-12">
            <div aria-label="breadcrumb" class="float-right mt-1">
                <a class="btn btn-primary" href="{{route('admin.page.index')}}">Danh sách</a>
            </div>
            <span><b> <a class="text-dark" href="{{route('admin.page.index')}}">Danh sách</a> / <a class="text-dark" href="javascript:void(0)"> Sửa</a> </b></span>
        </div>
    </div>
</section>

<section class="content">
    <div class="card">
        <div class="card-body">
            <form role="form" action="{{route('admin.page.update', ['id' => $page->id ])}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="box-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Tiêu Đề</label>
                        <input value="{{$page->title}}" type="text" class="form-control" id="title" name="title" placeholder="Nhập tên">
                        @error('title')
                        <label class="col-lg-12 col-form-label text-danger">{{ $message }}</label>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Url(Liên kết tùy chỉnh)</label>
                        <input value="{{$page->slug}}" type="text" class="form-control" id="slug" name="slug" placeholder="Nhập liên kết tùy chỉnh">
                    </div>
                    <div class="form-group">
                        <label for="description">Mô tả</label>
                        <textarea   id="editor1" name="description" class="form-control" rows="10" >{{$page->description}}</textarea>
                    </div>
                    <div class="form-group mb-3">
                        <div class="custom-control custom-switch mb-2">
                            <input  type="checkbox" class="custom-control-input" id="customSwitch1" {{ ($page->is_active) ? 'checked':'' }}  value="1"  name="is_active">
                            <label class="custom-control-label" for="customSwitch1">Trạng thái</label>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Lưu</button>
            </form>

        </div>
    </div>
    <!-- /.row -->
</section>
@endsection

@section('my_javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            $(".btn-success").click(function(){
                var html = $(".clone").html();
                $(".increment").after(html);
            });
            $("body").on("click",".btn-danger",function(){
                $(this).parents(".control-group").remove();
            });
        });
        $(document).ready(function() {
            // setup textarea sử dụng plugin CKeditor
            var _ckeditor = CKEDITOR.replace('editor1',{
                filebrowserBrowseUrl: '{{ asset('ckfinder/ckfinder.html') }}',
                filebrowserImageBrowseUrl: '{{ asset('backend/assets/js/pages/ckfinder/ckfinder.html?type=Images') }}',
                filebrowserFlashBrowseUrl: '{{ asset('backend/assets/js/pages/ckfinder/ckfinder.html?type=Flash') }}',
                filebrowserUploadUrl: '{{ asset('backend/assets/js/pages/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files') }}',
                filebrowserImageUploadUrl: '{{ asset('backend/assets/js/pages/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images') }}',
                filebrowserFlashUploadUrl: '{{ asset('backend/assets/js/pages/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash') }}',
                extraPlugins: 'image2'
            });
            _ckeditor.config.height = 200; // thiết lập chiều cao
        });
    </script>
@endsection

resources/views/admin/page/index.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="row page-title">
    <div class="col-md-12">
        <div aria-label="breadcrumb" class="float-right mt-1">
            <a class="btn btn-primary" href="{{route('admin.page.create')}}">Thêm mới</a>
        </div>
        <h4 class="mb-1 mt-0">Danh sách</h4>
    </div>
</div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table m-0">
                                <thead>
                                    <tr>
                                        <th>Tiêu đề</th>
                                        <th>Trạng thái</th>
                                        <th class="text-center">Hành động</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data as $key => $item)
                                <tr class="item-{{ $item->id }}"> <!-- Thêm Class Cho Dòng -->
                                    <td>{{ $item->title }}</td>

                                    <td>{{ ($item->is_active == 1) ? 'Hiển thị' : 'Ẩn' }}</td>
                                    <td class="text-center">

                                        <a class="btn btn-primary" href="{{route('admin.page.edit', ['id'=> $item->id ])}}">Sửa</a>
                                        <a class="btn btn-danger" href="javascript:void(0)" onclick="delete_model({{$item->id}},'page')">Xóa</a>
                                    </td>
                                </tr>
                            @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                             <ul class="pagination pagination-sm no-margin">
                                {{ $data->links() }} <!-- nút bấm phân trang -->
                            </ul> 
                        </div>

                    </div>
                </div>

            </div>
        </div>
        <!-- /.row -->
@endsection