routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Trang chủ
Route::get('/', 'ShopController@index')->name('shop.home');
// Liên Hệ

// Chi tiet sản phẩn
Route::get('/chi-tiet-san-pham/{slug}_{id}', 'ShopController@getProduct')->name('shop.product');

// Tìm kiếm
Route::get('/tim-kiem', 'ShopController@search')->name('shop.search');

// Thêm sản phẩm vào giỏ hàng hompage
Route::get('/dat-hang/them-sp-vao-gio-hang/{id}', 'CartController@addToCart')->name('shop.cart.add-to-cart');

// Xóa SP khỏi giỏ hàng
Route::get('/dat-hang/xoa-sp-gio-hang/{id}', 'CartController@removeToCart')->name('shop.cart.remove-to-cart');

//Them san pham trong gio hang
Route::get('/dat-hang/xem-san-pham-trong-gio-hang/', 'CartController@ViewListCart')->name('shop.cart.add-view-cart');


// Cập nhật giỏ hàng
Route::get('/dat-hang/cap-nhat-gio-hang/{id}/{quanty}', 'CartController@SaveListItemCart')->name('shop.cart.update-to-cart');

// Áp dụng giảm giá
Route::get('/dat-hang/ma-giam-gia', 'CartController@checkCoupon')->name('shop.cart.check-coupon');


// Hủy đơn hàng
Route::get('/dat-hang/huy-don-hang', 'CartController@destroy')->name('shop.cart.destroy');

// Đặt hàng
Route::get('/dat-hang', 'CartController@index')->name('shop.cart');
// Thanh toán
Route::get('/thanh-toan', 'CartController@checkout')->name('shop.cart.checkout');

Route::post('/thanh-toan', 'CartController@postCheckout')->name('shop.cart.checkout');
// // Thanh toán
Route::get('/lien-he', 'ContactController@create')->name('shop.contact');

Route::post('/lien-he', 'ContactController@store')->name('shop.contact.store');
// Route::resource('contact', 'ContactController');
//comments
Route::post('/comment/{blog_id}','CommentController@createBlog')->name('comments.create');
Route::post('/comments/{product_id}','CommentController@store')->name('comments.store');

/////////////////////////////////////////
// Đăng nhập
Route::get('/admin/login', 'AdminController@login')->name('admin.login');

// Đăng xuất
Route::get('/admin/logout', 'AdminController@logout')->name('admin.logout');
//tra cứu
Route::get('/tk', 'ShopController@sorder')->name('shop.sorder');
Route::get('/tra-cuu', 'ShopController@viewsearchorder')->name('shop.viewsearchorder');
Route::post('/admin/postLogin', 'AdminController@postLogin')->name('admin.postLogin');
Route::group(['prefix' => 'admin','as' => 'admin.','middleware' => ['CheckLogin']], function() {

	Route::get('/', 'AdminController@index')->name('dashboard');

    // Router cho category
	Route::resource('category', 'CategoryController');

    // Router cho Vendor
	   Route::resource('vendor','VendorController');


   	// Router cho Banner
	   Route::resource('banner','BannerController');

   	// Router cho Brand
	   Route::resource('brand','BrandController');
	   Route::get('searchBrand','BrandController@searchBrand');

   	// Router cho Product
	   Route::resource('product','ProductController');
	   Route::get('searchProduct','ProductController@searchProduct');

   	// Router cho User
	   Route::resource('user','UserController');

	// Router cho Image Product
	   Route::resource('imageUpload','ImageUploadController');

   	// Router cho Blog
   		Route::resource('blog','BlogController');
   		Route::get('searchBlog','BlogController@searchBlog');

   	// Router cho Order
   		Route::resource('order','OrderController');
   		Route::get('searchOrder','OrderController@searchOrder');

   	// Router cho Contact
   		Route::get('contact','ContactController@index')->name('contact.index');
   		Route::get('contact/{contact}/edit','ContactController@edit')->name('contact.edit');
   		Route::put('contact/{contact}','ContactController@update')->name('contact.update');
   		Route::patch('contact/{contact}','ContactController@update')->name('contact.update');
   		Route::get('searchContact','ContactController@searchContact');

   	// Router cho Coupon
   		Route::resource('coupon', 'CouponController');
   		Route::get('searchCoupon','CouponController@searchCoupon');

   	 // Cau Hinh Website
        Route::resource('setting', 'SettingController');
   		Route::resource('page', 'PageController');
   		Route::resource('AboutUs','AboutUsController');
   		Route::get('listicon','ListIconController@index')->name('listicon');
});
Route::get('forgot-password','AdminController@forgot')->name('forgot');
Route::post('forgot-password','AdminController@getForgotPassword')->name('getForgot');
Route::get('resetPassword/{token}','AdminController@resetPassword')->name('resetPassword');
Route::post('resetPassword','AdminController@newPass')->name('newPass');
//
Route::get('/danh-muc/{slug}', 'ShopController@getProductsByCategory')->name('shop.category');
Route::get('/blogs-detalis/{slug}_{id}.html', 'ShopController@ViewBlog')->name('shop.blog');
Route::get('/blogs-detalis', 'ShopController@BlogDetails')->name('shop.blog-detalis');
Route::get('/danh-muc/{slug}/filter','ShopController@filter')->name('shop.filter');
Route::get('/{slug}/{id}', 'ShopController@getpage')->name('shop.page');
Route::get('/{slug}', 'GeneralController@notfound')->name('shop.notfound');

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $table = "images";
}

resources/views/admin/image/create.blade.php
@extends('admin.layout.main')
@section('content')
    <div class="row page-title">
                            <div class="col-md-12">
                                <div aria-label="breadcrumb" class="float-right mt-1">
                                    <a class="btn btn-primary" href="{{route('admin.vendor.index')}}">Danh sách</a>
                                </div>
                                <h4 class="mb-1 mt-0">Thêm mới</h4>
                            </div>
    </div>
	<h3 class="text-center" style="margin-top: 50px;">Laravel Multiple Image Upload Using DropzoneJS</h3><br>
    <form method="post" action="{{url('admin/image')}}" enctype="multipart/form-data"
          class="dropzone" id="dropzone">
        @csrf
    </form>
    <script type="text/javascript">
        Dropzone.options.dropzone =
            {
                maxFilesize: 12,
                renameFile: function (file) {
                    var dt = new Date();
                    var time = dt.getTime();
                    return time + file.name;
                },
                acceptedFiles: ".jpeg,.jpg,.png,.gif",
                addRemoveLinks: true,
                timeout: 50000,
                removedfile: function (file) {
                    var name = file.upload.filename;
                    $.ajax({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                        },
                        type: 'POST',
                        url: '{{ url("admin/delete") }}',
                        data: {filename: name},
                        success: function (data) {
                            console.log("File has been successfully removed!!");
                        },
                        error: function (e) {
                            console.log(e);
                        }
                    });
                    var fileRef;
                    return (fileRef = file.previewElement) != null ?
                        fileRef.parentNode.removeChild(file.previewElement) : void 0;
                },

                success: function (file, response) {
                    console.log(response);
                },
                error: function (file, response) {
                    return false;
                }
            };
    </script>
@endsection

resources/views/admin/image/edit.blade.php
@extends('admin.layout.main')
@section('content')
    <div class="row page-title">
                            <div class="col-md-12">
                                <div aria-label="breadcrumb" class="float-right mt-1">
                                    <a class="btn btn-primary" href="{{route('admin.vendor.index')}}">Danh sách</a>
                                </div>
                                <h4 class="mb-1 mt-0">Sửa</h4>
                            </div>
    </div>
	<div class="row">
                            <div class="col-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="header-title mt-0">Sửa Vendor</h4>
                                        <form class="form-horizontal" form role="form" action="{{route('admin.vendor.update',['id'=>$data->id])}}" method="post" enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')
                                           <div class="row">
                                               <div class="col">
                                                   <div class="form-group row">
                                                        <label class="col-lg-2 col-form-label" for="simpleinput">Tên</label>
                                                        <div class="col-lg-10">
                                                            <input type="text" class="form-control" id="simpleinput" name="name" value="{{$data->name}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label class="col-lg-2 col-form-label" for="simpleinput">Email</label>
                                                        <div class="col-lg-10">
                                                            <input type="text" class="form-control" id="simpleinput" name="email" value="{{$data->email}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label class="col-lg-2 col-form-label" for="simpleinput">SĐT</label>
                                                        <div class="col-lg-10">
                                                            <input type="number" class="form-control" id="simpleinput" name="phone" value="{{$data->phone}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label class="col-lg-2 col-form-label" for="example-fileinput">Ảnh</label>
                                                        <div class="col-lg-10">
                                                            <input type="file" class="form-control" id="example-fileinput" name="new_image">
                                                            <img src="{{asset($data->image)}}" alt="{{$data->name}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label class="col-lg-2 col-form-label" for="simpleinput">Website</label>
                                                        <div class="col-lg-10">
                                                            <input type="text" class="form-control" id="simpleinput" name="website" value="{{$data->website}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label class="col-lg-2 col-form-label" for="simpleinput">Địa chỉ</label>
                                                        <div class="col-lg-10">
                                                            <input type="text" class="form-control" id="simpleinput" name="address" value="{{$data->address}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <label class="col-lg-2 col-form-label">Vị trí</label>
                                                        <div class="col-lg-10">
                                                            <input type="number" class="form-control" name="position" value="{{$data->position}}">
                                                        </div>
                                                    </div>
                                                    <div class="custom-control custom-switch mb-2">
                                                        <input type="checkbox" class="custom-control-input" id="customSwitch1"  name="is_active" value="1" {{$data->is_active ? 'checked' : '' }}>
                                                        <label class="custom-control-label" for="customSwitch1">Trạng thái</label>
                                                    </div>
                                                     <button type="submit" class="btn btn-primary">Sửa</button>
                                               </div>

                                           </div>
                                        </form>
            
                                    </div> <!-- end card-body -->
                                </div> <!-- end card-->
                            </div><!-- end col -->
            </div>
@endsection

resources/views/admin/image/index.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="row page-title">
    <div class="col-md-12">
        <div aria-label="breadcrumb" class="float-right mt-1">
            <a class="btn btn-primary" href="{{route('admin.page.create')}}">Thêm mới</a>
        </div>
        <h4 class="mb-1 mt-0">Danh sách</h4>
    </div>
</div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table m-0">
                                <thead>
                                    <tr>
                                        <th>Tiêu đề</th>
                                        <th>Trạng thái</th>
                                        <th class="text-center">Hành động</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data as $key => $item)
                                <tr class="item-{{ $item->id }}"> <!-- Thêm Class Cho Dòng -->
                                    <td>{{ $item->title }}</td>

                                    <td>{{ ($item->is_active == 1) ? 'Hiển thị' : 'Ẩn' }}</td>
                                    <td class="text-center">

                                        <a class="btn btn-primary" href="{{route('admin.page.edit', ['id'=> $item->id ])}}">Sửa</a>
                                        <a class="btn btn-danger" href="javascript:void(0)" onclick="delete_model({{$item->id}},'page')">Xóa</a>
                                    </td>
                                </tr>
                            @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="box-footer clearfix">
                            {{-- <ul class="pagination pagination-sm no-margin">
                                {{ $data->links() }} nút bấm phân trang
                            </ul> --}}
                        </div>

                    </div>
                </div>

            </div>
        </div>
        <!-- /.row -->
@endsection