routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Trang chủ
Route::get('/', 'ShopController@index')->name('shop.home');
// Liên Hệ

// Chi tiet sản phẩn
Route::get('/chi-tiet-san-pham/{slug}_{id}', 'ShopController@getProduct')->name('shop.product');

// Tìm kiếm
Route::get('/tim-kiem', 'ShopController@search')->name('shop.search');

// Thêm sản phẩm vào giỏ hàng hompage
Route::get('/dat-hang/them-sp-vao-gio-hang/{id}', 'CartController@addToCart')->name('shop.cart.add-to-cart');

// Xóa SP khỏi giỏ hàng
Route::get('/dat-hang/xoa-sp-gio-hang/{id}', 'CartController@removeToCart')->name('shop.cart.remove-to-cart');

//Them san pham trong gio hang
Route::get('/dat-hang/xem-san-pham-trong-gio-hang/', 'CartController@ViewListCart')->name('shop.cart.add-view-cart');


// Cập nhật giỏ hàng
Route::get('/dat-hang/cap-nhat-gio-hang/{id}/{quanty}', 'CartController@SaveListItemCart')->name('shop.cart.update-to-cart');

// Áp dụng giảm giá
Route::get('/dat-hang/ma-giam-gia', 'CartController@checkCoupon')->name('shop.cart.check-coupon');


// Hủy đơn hàng
Route::get('/dat-hang/huy-don-hang', 'CartController@destroy')->name('shop.cart.destroy');

// Đặt hàng
Route::get('/dat-hang', 'CartController@index')->name('shop.cart');
// Thanh toán
Route::get('/thanh-toan', 'CartController@checkout')->name('shop.cart.checkout');

Route::post('/thanh-toan', 'CartController@postCheckout')->name('shop.cart.checkout');
// // Thanh toán
Route::get('/lien-he', 'ContactController@create')->name('shop.contact');

Route::post('/lien-he', 'ContactController@store')->name('shop.contact.store');
// Route::resource('contact', 'ContactController');
//comments
Route::post('/comment/{blog_id}','CommentController@createBlog')->name('comments.create');
Route::post('/comments/{product_id}','CommentController@store')->name('comments.store');

/////////////////////////////////////////
// Đăng nhập
Route::get('/admin/login', 'AdminController@login')->name('admin.login');

// Đăng xuất
Route::get('/admin/logout', 'AdminController@logout')->name('admin.logout');
//tra cứu
Route::get('/tk', 'ShopController@sorder')->name('shop.sorder');
Route::get('/tra-cuu', 'ShopController@viewsearchorder')->name('shop.viewsearchorder');
Route::post('/admin/postLogin', 'AdminController@postLogin')->name('admin.postLogin');
Route::group(['prefix' => 'admin','as' => 'admin.','middleware' => ['CheckLogin']], function() {

	Route::get('/', 'AdminController@index')->name('dashboard');

    // Router cho category
	Route::resource('category', 'CategoryController');

    // Router cho Vendor
	   Route::resource('vendor','VendorController');


   	// Router cho Banner
	   Route::resource('banner','BannerController');

   	// Router cho Brand
	   Route::resource('brand','BrandController');
	   Route::get('searchBrand','BrandController@searchBrand');

   	// Router cho Product
	   Route::resource('product','ProductController');
	   Route::get('searchProduct','ProductController@searchProduct');

   	// Router cho User
	   Route::resource('user','UserController');

	// Router cho Image Product
	   Route::resource('imageUpload','ImageUploadController');

   	// Router cho Blog
   		Route::resource('blog','BlogController');
   		Route::get('searchBlog','BlogController@searchBlog');

   	// Router cho Order
   		Route::resource('order','OrderController');
   		Route::get('searchOrder','OrderController@searchOrder');

   	// Router cho Contact
   		Route::get('contact','ContactController@index')->name('contact.index');
   		Route::get('contact/{contact}/edit','ContactController@edit')->name('contact.edit');
   		Route::put('contact/{contact}','ContactController@update')->name('contact.update');
   		Route::patch('contact/{contact}','ContactController@update')->name('contact.update');
   		Route::get('searchContact','ContactController@searchContact');

   	// Router cho Coupon
   		Route::resource('coupon', 'CouponController');
   		Route::get('searchCoupon','CouponController@searchCoupon');

   	 // Cau Hinh Website
        Route::resource('setting', 'SettingController');
   		Route::resource('page', 'PageController');
   		Route::resource('AboutUs','AboutUsController');
   		Route::get('listicon','ListIconController@index')->name('listicon');
});
Route::get('forgot-password','AdminController@forgot')->name('forgot');
Route::post('forgot-password','AdminController@getForgotPassword')->name('getForgot');
Route::get('resetPassword/{token}','AdminController@resetPassword')->name('resetPassword');
Route::post('resetPassword','AdminController@newPass')->name('newPass');
//
Route::get('/danh-muc/{slug}', 'ShopController@getProductsByCategory')->name('shop.category');
Route::get('/blogs-detalis/{slug}_{id}.html', 'ShopController@ViewBlog')->name('shop.blog');
Route::get('/blogs-detalis', 'ShopController@BlogDetails')->name('shop.blog-detalis');
Route::get('/danh-muc/{slug}/filter','ShopController@filter')->name('shop.filter');
Route::get('/{slug}/{id}', 'ShopController@getpage')->name('shop.page');
Route::get('/{slug}', 'GeneralController@notfound')->name('shop.notfound');

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\Admin;
use App\Order;
use Illuminate\Http\Request;

class UserController extends AdminGeneralController
{

    public function index()
    {
        $data = Admin::latest()->paginate(10); // sắp sếp theo thứ tự mới nhất && phân trang
        // gọi đến view
        return view('admin.user.index', [
            'data' => $data // truyền dữ liệu sang view Index
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Admin::all(); // lấy toàn bộ dữ liệu
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email',
            'password' => 'required|min:6',
            'avatar' => 'image|mimes:jpeg,png,jpg,gif,svg|max:10000'
        ]);
        $user = new Admin();
        $is_active = 0;
        if ($request->has('is_active')) { // kiem tra is_active co ton tai khong?
            $is_active = $request->input('is_active');
        }
        $user->is_active = $is_active;
        //luu vào csdl

        $user->name = $request->input('name'); // họ tên
        $user->email = $request->input('email'); // email
        $password = $request->input('password');
        $user->password = bcrypt("$password"); // mật khẩu
        $user->role_id = $request->input('role_id'); // phần quyền

        if ($request->hasFile('avatar')) {
            // get file
            $file = $request->file('avatar');
            // get ten
            $filename = time().'_'.$file->getClientOriginalName();
            // duong dan upload
            $path_upload = 'uploads/user/';
            // upload file
            $request->file('avatar')->move($path_upload,$filename);

            $user->avatar = $path_upload.$filename;
        }

        $user->save();

        // chuyen dieu huong trang
        return redirect()->route('admin.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('admin.user.show',[
            'user' => $user
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Admin::findOrFail($id);
        return view('admin.user.edit',[
            'user' => $user
        ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
                //validate
        $validatedData = $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email',
            'avatar' => 'image|mimes:jpeg,png,jpg,gif,svg|max:30000'
        ]);

        $user = Admin::findorFail($id);

        $is_active = 0;
        if ($request->has('is_active')) { // kiem tra is_active co ton tai khong?
            $is_active = $request->input('is_active');
        }

        //luu vào csdl
        $user->name = $request->input('name'); // họ tên
        $user->email = $request->input('email'); // email
        $user->role_id = $request->input('role_id'); // phần quyền

        if ($request->input('new_password')) {
            $user->password = bcrypt($request->input('new_password')); // mật khẩu mới
        }

        if ($request->hasFile('new_avatar')) {
            // xóa file cũ
            @unlink(public_path($user->avatar)); // hàm unlink của PHP không phải laravel , chúng ta thêm @ đằng trước tránh bị lỗi
            // get file
            $file = $request->file('new_avatar');
            // get ten
            $filename = time().'_'.$file->getClientOriginalName();
            // duong dan upload
            $path_upload = 'uploads/user/';
            // upload file
            $request->file('new_avatar')->move($path_upload,$filename);

            $user->avatar = $path_upload.$filename;
        }

        $user->is_active = $is_active;
        $user->save();

        // chuyen dieu huong trang
        return redirect()->route('admin.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // gọi tới hàm destroy của laravel để xóa 1 object
       Admin::destroy($id);

       // Trả về dữ liệu json và trạng thái kèm theo thành công là 200
       return response()->json([
           'status' => true
       ], 200);
   }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="row page-title">
    <div class="col-md-12">
        <div aria-label="breadcrumb" class="float-right mt-1">
            <a class="btn btn-primary" href="{{route('admin.user.index')}}">Danh sách</a>
        </div>
        <span><b> <a class="text-dark" href="{{route('admin.user.index')}}">Danh sách</a> / <a class="text-dark" href="javascript:void(0)"> Thêm mới Usẻ</a> </b></span>
    </div>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <h4 class="header-title mt-0">Thêm mới User</h4>
            <form class="form-horizontal" form role="form" action="{{route('admin.user.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                 <div class="col">
                    <div class="form-group row">
                        <select class="custom-select mb-2" name="role_id">
                            <option selected="" value="0">Lựa chọn quyền</option>
                            <option value="1">Quản trị viên</option>
                            <option value="2">Cộng tác viên</option>
                        </select>

                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label"  for="simpleinput">Tên</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" value="{{old('name')}}" id="simpleinput" name="name">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label"  for="simpleinput">Email</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" value="{{old('email')}}" id="simpleinput" name="email">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-3 col-form-label" for="simpleinput">Password</label>
                        <div class="col-lg-9">
                            <input type="text" class="form-control" id="simpleinput" name="password">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label" for="example-fileinput">Ảnh</label>
                        <div class="col-lg-10">
                            <input type="file" class="form-control" id="example-fileinput" name="image">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label">Vị trí</label>
                        <div class="col-lg-10">
                            <input type="number" class="form-control" name="position">
                        </div>
                    </div>
                    <div class="custom-control custom-switch mb-2">
                        <input type="checkbox" class="custom-control-input" id="customSwitch1"  name="is_active" value="1">
                        <label class="custom-control-label" for="customSwitch1">Trạng thái</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            </div>
        </form>

    </div> <!-- end card-body -->
</div> <!-- end card-->
</div><!-- end col -->
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.main')
@section('content')
<section class="content-header">
    <div class="row page-title">
        <div class="col-md-12">
            <div aria-label="breadcrumb" class="float-right mt-1">
                <a class="btn btn-primary" href="{{route('admin.user.index')}}">Danh sách</a>
            </div>
            <span><b> <a class="text-dark" href="{{route('admin.user.index')}}">Danh sách</a> / <a class="text-dark" href="javascript:void(0)"> Sửa thông tin user</a> </b></span>
        </div>
    </div>
</section>

<section class="content">
    <div class="card">
        <div class="card-body">

            <form role="form" action="{{route('admin.user.update', ['id'=>$user->id])}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="box-body">
                    <div class="form-group">
                        <label>Chọn Quyền</label>
                        <select class="form-control" name="role_id">
                            <option value="1" {{ ($user->role_id == 1) ? 'selected' : '' }}>Manager</option>
                            <option value="2" {{ ($user->role_id == 2) ? 'selected' : '' }}>Administrator</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Họ Tên</label>
                        <input value="{{ $user->name }}" type="text" class="form-control" id="name" name="name" placeholder="Nhập họ & tên">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email</label>
                        <input value="{{ $user->email }}" type="text" class="form-control" id="email" name="email" placeholder="Nhập Email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1" > Mật khẩu mới</label>
                        <input type="password" class="form-control" id="new_password" name="new_password" placeholder="Nhập mật khẩu mới">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile" > Thay đổi ảnh đại diện</label> <br>
                        <input type="file" id="new_avatar" name="new_avatar">
                        <br>
                        <img src="{{ asset($user->avatar) }}" width="250">
                        <div class="form-group mb-3">
                            <div class="custom-control custom-checkbox form-check">
                                <input  type="checkbox" class="custom-control-input" id="invalidCheck" value="1" name="is_active"  {{ ($user->is_active == 1) ? 'checked' : '' }}>
                                <label class="custom-control-label" for="invalidCheck">Kích hoạt </label>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Cập nhật</button>
                    </div>
                </form>

            </div>
        </div>
        <!-- /.row -->
    </section>
    @endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="row page-title">
                            <div class="col-md-12">
                                <div aria-label="breadcrumb" class="float-right mt-1">
                                    <a class="btn btn-primary" href="{{route('admin.user.create')}}">Thêm mới</a>
                                </div>
                                <h4 class="mb-1 mt-0">Danh sách</h4>
                            </div>
</div>
                <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-body">

                                        <div class="table-responsive">
                                            <table class="table m-0">
                                                <thead>
                                                    <tr>
                                                        <th>Tên</th>
                                                        <th>Avatar</th>
                                                        <th>Email</th>
                                                        <th>Quyền</th>
                                                        <th>Trạng Thái</th>
                                                        <th>Vị trí</th>
                                                        <th class="text-center">Hành động</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                	@foreach($data as $key => $item)
                                                    <tr class="item-{{$item->id}}">
                                                        <td>{{$item->name}}</td>
                                                        <td>
                                                            @if ($item->avatar) <!-- Kiểm tra hình ảnh tồn tại -->
                                                                <img src="{{asset($item->avatar)}}" width="50" height="50">
                                                            @endif
                                                        </td>
                                                        <td>{{$item->email}}</td>
                                                        @if($item->role_id == 1)
                                                        <td>Quản trị viên</td>
                                                        @elseif($item->role_id == 2)
                                                        <td>Cộng tác viên</td>
                                                        @else
                                                        <td>Chưa phân quyền</td>
                                                        @endif
                                                        <td>{{$item->is_active !=0 ? 'Hiển thị' : 'Ẩn'  }}</td>
                                                        <td>{{$item->position}}</td>
                                                        <td>
                                                            
                                                            <a class="btn btn-primary" href="{{route('admin.user.edit', ['id'=> $item->id ])}}">Sửa</a>
                                                            <a class="btn btn-danger" href="javascript:void(0)" onclick="delete_model({{$item->id}},'user')">Xóa</a>
                                                        </td>
                                                    </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layouts.main')
@section('content')
@extends('admin.layouts.main')
@section('content')
<div class="row page-title">
    <div class="col-md-12">
        <div aria-label="breadcrumb" class="float-right mt-1">
            <a class="btn btn-primary" href="{{route('admin.user.index')}}">Danh sách</a>
        </div>
        <span><b> <a class="text-dark" href="{{route('admin.user.index')}}">Danh sách</a> / <a class="text-dark" href="javascript:void(0)"> Chi tiết user</a> </b></span>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">


                <div class="table-responsive">
                    <table class="table m-0">
                        <tbody>
                            <tr>
                                <td><b>Tên danh mục:</b></td>
                                <td>{{ $user->name }}</td>
                            </tr>
                            <tr>
                                <td><b>Hình ảnh:</b></td>
                                <td>
                                    @if ($user->avatar) <!-- Kiểm tra hình ảnh tồn tại -->
                                    <img src="{{asset($user->avatar)}}" width="50" height="50">
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <td><b>Danh mục cha:</b></td>
                                <td>{{ $user->parent['name'] ? $user->parent['name'] : '(trống)' }}</td>
                            </tr>
                            <tr>
                               <td><b>Vị trí:</b></td>
                               <td>{{ $user->position }}</td>
                           </tr>
                           <tr>
                               <td><b>Trạng thái</b></td>
                               <td>{{ $user->is_active ? 'Hiện' : 'Ẩn' }}</td>
                           </tr>
                       </tbody>
                   </table>
               </div>
           </div>
       </div>

   </div>
</div>
@endsection
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title mt-0 mb-1">Category</h4>

                <div class="table-responsive">
                    <table class="table m-0">
                        <tbody>
                            <tr>
                                <td><b>Tên danh mục:</b></td>
                                <td>{{ $user->name }}</td>
                            </tr>
                            <tr>
                                <td><b>Hình ảnh:</b></td>
                                <td>
                                    @if ($user->avatar) <!-- Kiểm tra hình ảnh tồn tại -->
                                    <img src="{{asset($user->avatar)}}" width="50" height="50">
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <td><b>Danh mục cha:</b></td>
                                <td>{{ $user->parent['name'] ? $user->parent['name'] : '(trống)' }}</td>
                            </tr>
                            <tr>
                               <td><b>Vị trí:</b></td>
                               <td>{{ $user->position }}</td>
                           </tr>
                           <tr>
                               <td><b>Trạng thái</b></td>
                               <td>{{ $user->is_active ? 'Hiện' : 'Ẩn' }}</td>
                           </tr>
                       </tbody>
                   </table>
               </div>
           </div>
       </div>

   </div>
</div>
@endsection